
# This file describes the environment of the Ubuntu 12.04 LTS virtual machine 
# used to bootstrap GNU/Minix.

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Ubuntu 12.04 LTS
  config.vm.box = "precise32"

  # get box from vagrant website, if not available
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  # attach the virtual disk that holds GNU/Minix
  config.vm.provider :virtualbox do |vb|
    vb.customize ['createhd', '--filename', '../minix_disk.vdi', '--size', 500 * 1024]
    vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', '../minix_disk.vdi']
  end
end
